logging:
  level.root: DEBUG

server:
  port: 9092

spring:
  application:
    name: gateway-service # Name of the microservice as registered with Spring Cloud.
  profiles:
    active: gateway # Active profile, which could control various aspects of the application behavior based on the active environment.
  config:
    import: 'configserver:' # Refers to a Spring Cloud Config server from which this service will fetch its externalized configuration.
  cloud:
    config:
      name: gateway-service,config-client # Configuration names this application is associated with on the Config Server.
      username: spring_cloud_user # Username for authentication with the Config Server.
      password: '1234' # Password for authentication with the Config Server.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server where this service will register itself.
  instance:
    lease-expiration-duration-in-seconds: 5 # Time in seconds after which a service instance is eligible for removal if it has not sent a heartbeat.
    lease-renewal-interval-in-seconds: 2 # Time interval in seconds at which this service instance will send heartbeats to the Eureka server.

log:
  app-name: gateway-service